export const estadosVerificarCuenta = {
  SUBIDA_ARCHIVOS_PENDIENTE: 'SUBIDA DE ARCHIVOS PENDIENTE',
  EN_ESPERA_VERIFICACION: 'EN ESPERA DE VERIFICACION',
  VERIFICADO: 'VERIFICADO',
  NO_CUMPLE: 'USTED NO CUMPLE CON LOS PARAMETROS INTEGRALES ESTABLECIDOS POR TRABAJOS ECUADOR PARA PARTICIPAR DENTRO DEL PROCESO DE RECLUTAMIENTO',
}

export const opcionesVerificarCuenta = [
  estadosVerificarCuenta.SUBIDA_ARCHIVOS_PENDIENTE,
  estadosVerificarCuenta.EN_ESPERA_VERIFICACION,
  estadosVerificarCuenta.VERIFICADO,
  estadosVerificarCuenta.NO_CUMPLE,
]
