import { ColumnConfig } from 'components/tables/domain/ColumnConfig'
import { RegistroCivil } from './RegistroCivil'

export const configuracionColumnasRegistroCivil: ColumnConfig<RegistroCivil>[] =
  [
    {
      name: 'cedula',
      field: 'cedula',
      label: 'Cédula',
      align: 'left',
      sortable: true,
    },
    {
      name: 'apellidos_nombres',
      field: 'apellidos_nombres',
      label: 'Apellidos y nombres',
      align: 'left',
      sortable: true,
    },
    {
      name: 'sexo',
      field: 'sexo',
      label: 'Sexo',
      align: 'left',
      sortable: true,
    },
    {
      name: 'condicion',
      field: 'condicion',
      label: 'Condición',
      align: 'left',
      sortable: true,
    },
    {
      name: 'fecha_nacimiento',
      field: 'fecha_nacimiento',
      label: 'Fecha de nacimiento',
      align: 'left',
      sortable: true,
    },
    {
      name: 'pais',
      field: 'pais',
      label: 'Pais',
      align: 'left',
      sortable: true,
    },
    {
      name: 'estado_civil',
      field: 'estado_civil',
      label: 'Estado civil',
      align: 'left',
      sortable: true,
    },
    {
      name: 'conyugue',
      field: 'conyugue',
      label: 'Conyugue',
      align: 'left',
      sortable: true,
    },
    {
      name: 'cedula_conyugue',
      field: 'cedula_conyugue',
      label: 'Cédula conyugue',
      align: 'left',
      sortable: true,
    },
    /*{
      name: 'apellidos_nombres_padre',
      field: 'apellidos_nombres_padre',
      label: 'Apellidos nombres padre',
      align: 'left',
      sortable: true,
    },
     {
      name: 'pais_padre',
      field: 'pais_padre',
      label: 'Pais padre',
      align: 'left',
      sortable: true,
    },
    {
      name: 'cedula_padre',
      field: 'cedula_padre',
      label: 'Cédula padre',
      align: 'left',
      sortable: true,
    },
    {
      name: 'apellidos_nombres_madre',
      field: 'apellidos_nombres_madre',
      label: 'Apellidos nombres madre',
      align: 'left',
      sortable: true,
    },
    {
      name: 'pais_madre',
      field: 'pais_madre',
      label: 'Pais madre',
      align: 'left',
      sortable: true,
    },
    {
      name: 'cedula_madre',
      field: 'cedula_madre',
      label: 'Cédula madre',
      align: 'left',
      sortable: true,
    },
    {
      name: 'direccion',
      field: 'direccion',
      label: 'Dirección',
      align: 'left',
      sortable: true,
    },
    {
      name: 'fecha_matrimonio',
      field: 'fecha_matrimonio',
      label: 'Fecha de matrimonio',
      align: 'left',
      sortable: true,
    },
    {
      name: 'puesto_ocupacion',
      field: 'puesto_ocupacion',
      label: 'Puesto u ocupación',
      align: 'left',
      sortable: true,
    }, */
    {
      name: 'instruccion',
      field: 'instruccion',
      label: 'Instrucción',
      align: 'left',
      sortable: true,
    },
    {
      name: 'fecha_emision',
      field: 'fecha_emision',
      label: 'Fecha de emisión',
      align: 'left',
      sortable: true,
    },
    {
      name: 'codigo_dactilar',
      field: 'codigo_dactilar',
      label: 'Código dactilar',
      align: 'left',
      sortable: true,
    },
  ]
