import { EntidadAuditable } from 'shared/entidad/domain/entidadAuditable'

export class Sri extends EntidadAuditable {
  numero_ruc: string | null = null
  razon_social: string | null = null
  nombre_fantasia_comercial: string | null = null
  fecha_inscripcion_ruc: string | null = null
  lista_blanca: string | null = null
  fecha_inicio_actividades: string | null = null
  valor_patrimonio: string | null = null
  obligado: string | null = null
  fecha_cancelacion: string | null = null
  pasaporte: string | null = null
  calificacion_artesanal: string | null = null
  fecha_calificacion_artesanal: string | null = null
  fecha_solicitud_suspension: string | null = null
  fecha_suspension_definitiva: string | null = null
  fecha_reinicio_actividades: string | null = null
  calle: string | null = null
  numero: string | null = null
  interseccion: string | null = null
  telefono: string | null = null
  correo_electronico: string | null = null
  referencia_ubicacion: string | null = null
  actividad_economica_principal: string | null = null
  categoria_rise: string | null = null
  clase_contribuyente: string | null = null
  estado_persona_natural: string | null = null
  fecha_actualizacion: string | null = null
  ubicacion_geografica: string | null = null
  actividad_contribuyente: string | null = null
  actividad_temporal: string | null = null
  provincia: string | null = null
  canton: string | null = null
  parroquia: string | null = null
  telefono_movistar: string | null = null
}
